### ISSUE TITLE
gin_browse_aliases name is different between documentation and code

### ISSUE THREAD

**Issue by kitagry** [lambdalisue/gin.vim#133]
Hi @lambdalisue. Thank you for the great plugin.

I try to use `:GinBrowse` in self hosted service. But, `g:gin_browse_aliases` doesn't work.
In [doc](https://github.com/lambdalisue/gin.vim/blob/main/doc/gin.txt#L520), the name is `g:gin_browse_aliases`, but in [code](https://github.com/lambdalisue/gin.vim/blob/main/denops/gin/command/browse/command.ts#L29), the name is `g:git_browse_aliases`.

**Comment by lambdalisue** [comment]
Thanks. That's a bug
