### ISSUE TITLE
Flags on `GinPatch` doesn't work

### ISSUE THREAD

**Issue by kg8m** [lambdalisue/gin.vim#37]
Hi. Thanks for developing gin.vim. I have been a long time fan of [gina.vim](https://github.com/lambdalisue/gina.vim) and am now migrating to gin.vim. I feel gin.vim is a great plugin too✨

I found a strange behavior of gin.vim's `GinPatch` command. Its flags `--without-head` and `--without-worktree` may not work. The head and the worktree buffers are always created even if the flags are given.

I think [`if (!flags["without-head"]) { ... }`](https://github.com/lambdalisue/gin.vim/blob/242e7b97fffe7fe611b9e6d5085429d341d30c73/denops/gin/feat/patch/command.ts#L39) is wrong because when the flag is given, the flag's value is an empty string (`""`) and falsy. Or gin.vim's parser may have a bug and the flag value may be unintentionally an empty string.

Best regards.

**Comment by lambdalisue** [comment]
Could you try https://github.com/lambdalisue/gin.vim/pull/39?

**Comment by kg8m** [comment]
Thank you for the quick fix! I have confirmed that #39 fixes the issue.

**Comment by kg8m** [comment]
Thank you!!✨
